FROM php:8.1-fpm

RUN apt update && apt install -y \
    git \
    curl \
    zip \
    vim \
    unzip \
    libicu-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql intl

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN bash -c "npm install && npm run dev"

COPY ./xdebug.ini "${PHP_INI_DIR}/conf.d"

WORKDIR /var/www
