version: '3.8'

services:
    app:
        build:
            context: ""
            dockerfile: DockerFile
        restart: always
        working_dir: /var/www
        volumes:
            - ../:/var/www
    nginx:
        image: nginx:latest
        container_name: nginx-series
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
    mysql:
        container_name: mysql
        image: mysql:8.0.32
        volumes:
            - ./storage/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
